### PR TITLE
🎫 fix: OAuth Token Endpoint Auth. Method Handling for FastMCP 2.14+ Compatibility

### LINKED ISSUE #11055: [Bug]: LibreChat Incompatible with FastMCP v2.14.0 because of RFC 6749 §4.1.3 handling
### What happened?

I maintain a popular MCP server and a contributor recently raised a [PR](https://github.com/taylorwilsdon/google_workspace_mcp/pull/308) with a shim fix that allows LibreChat to continue working with FastMCP v2.14.0 or later. FastMCP is the most popular python mcp sdk and rather than patch thousands of MCP servers individually with 300+ lines of code, it seems prudent to resolve the issue at the source by introducing compliant token payloads. 

It should be a simple fix - we simply need to ensure in `packages/api/src/mcp/oauth/handler.ts` that server-specific `oauth_headers` no longer override SDK-required headers during token exchange and ensure `Content-Type` stays `application/x-www-form-urlencoded` and `Authorization` (Basic/client_id) isn’t clobbered, preserving OAuth 2.0/2.1 compliance for `/token` requests.

Should be as simple as:
```diff
diff --git a/packages/api/src/mcp/oauth/handler.ts b/packages/api/src/mcp/oauth/handler.ts
index 7986e2ee5..ec9325eb8 100644
--- a/packages/api/src/mcp/oauth/handler.ts
+++ b/packages/api/src/mcp/oauth/handler.ts
@@ -33,8 +33,11 @@ export class MCPOAuthHandler {
   private static createOAuthFetch(headers: Record<string, string>): FetchLike {
     return async (url: string | URL, init?: RequestInit): Promise<Response> => {
       const newHeaders = new Headers(init?.headers ?? {});
       for (const [key, value] of Object.entries(headers)) {
-        newHeaders.set(key, value);
+        if (!newHeaders.has(key)) {
+          newHeaders.set(key, value);
+        }
       }
```

### Version Information

```
➜  LibreChat git:(main) git rev-parse HEAD

cd2813d5d7ebf19135bec99d46a32e731c00fdc7
```

### Steps to Reproduce

https://github.com/taylorwilsdon/google_workspace_mcp/pull/308

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

`https://github.com/taylorwilsdon/google_workspace_mcp/pull/308`

### Screenshots

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by owengo**
# Pull Request Template

⚠️ Before Submitting a PR, Please Review:
- Please ensure that you have thoroughly read and understood the [Contributing Docs](https://github.com/danny-avila/LibreChat/blob/main/.github/CONTRIBUTING.md) before submitting your Pull Request.

⚠️ Documentation Updates Notice:
- Kindly note that documentation updates are managed in this repository: [librechat.ai](https://github.com/LibreChat-AI/librechat.ai)

## Summary

Please provide a brief summary of your changes and the related issue. Include any motivation and context that is relevant to your changes. If there are any dependencies necessary for your changes, please list them here.

fixes: https://github.com/danny-avila/LibreChat/issues/11055

## Change Type

Please delete any irrelevant options.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Translation update

## Testing

Please describe your test process and include instructions so that we can reproduce your test. If there are any important variables for your testing configuration, list them here.

I have tested compatibilty with google_workspace_mcp 1.6.+ , which has updated its fastmcp module.

### **Test Configuration**:

The librechat.yaml requires a configuration like this:
```yaml
mcpServers:
  google_workspace:
    type: streamable-http
    url: http://127.0.0.1:8000/mcp/
    requiresOAuth: true
    startup: false
    oauth:
      token_exchange_method: "default_post"    
```

With this patch the post to /token works again

Note that tool calling fails because the mcp server does not use the access token to extract the user email ( requires a fix on the server side )

## Checklist

Please delete any irrelevant options.

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [ ] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [ ] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [ ] Any changes dependent on mine have been merged and published in downstream modules.
- [ ] A pull request for updating the documentation has been submitted.

### CODE REVIEW

File: packages/api/src/mcp/oauth/handler.ts [hunk 1]
```diff
@@ -739,9 +842,9 @@ export class MCPOAuthHandler {
         }
 
         const headers: HeadersInit = {
-          'Content-Type': 'application/x-www-form-urlencoded',
-          Accept: 'application/json',
           ...oauthHeaders,
+          Accept: 'application/json',
```
Comment (danny-avila) [inline packages/api/src/mcp/oauth/handler.ts:878]: What if OAuth headers are explicitly configured by the admin? This would override them every time.

File: packages/api/src/mcp/oauth/handler.ts [hunk 2]
```diff
@@ -663,17 +754,29 @@ export class MCPOAuthHandler {
...
```
Comment (danny-avila) [inline packages/api/src/mcp/oauth/handler.ts:799]: What if OAuth headers are explicitly configured by the admin? This would override them every time.

**Review by danny-avila — CHANGES_REQUESTED** [review]

File: packages/api/src/mcp/oauth/handler.ts (hunk 1 above)
Comment (owengo) [reply packages/api/src/mcp/oauth/handler.ts:878]: fixed  as requested

File: packages/api/src/mcp/oauth/handler.ts (hunk 2 above)
Comment (owengo) [reply packages/api/src/mcp/oauth/handler.ts:799]: fixed  as requested
