### PR TITLE
💾 feat: Custom Endpoint Support for Memory LLM Config 

### LINKED ISSUE #11012: [Bug]: Memory LLM config doesn't honor custom endpoint configuration
### What happened?

We are implementing the Memory feature. Our `librechat.yaml` file specifies mostly custom endpoints - we are hoping to retire the azureOpenAI endpoint (see [this discussion](https://github.com/danny-avila/LibreChat/discussions/10193#discussioncomment-14916218) for details).

When pointing the `memory.agent` configuration item to either the ID value of an agent pointing at a custom endpoint or directly to a custom endpoint via the `provider` and `model` items, custom headers configured under that custom endpoint which point to an environment variable are not getting expanded. In our implementation this causes authentication to fail, because we have to send over a custom `api-key` header. We have the following custom headers defined:

```
X-User-Identifier: "{{LIBRECHAT_USER_EMAIL}}"
X-Application-Identifier: "LibreChat - Dev"
api-key: "${LIBRECHAT_SUBSCRIPTION_KEY}"
```

Viewing our API gateway logs, the custom headers are getting sent over, but the ones which are pointing to environment variables are not getting expanded - it's just sending over the raw value.

In our scenario, this causing auth to fail for the memory calls.

As a temporary workaround, I've pointed the memory config to an azureOpenAI endpoint, as that is properly expanding environment variables.

### Version Information

da108155663f8aaab4e9d83e8a45aba273f0f7aa

### Steps to Reproduce

Set up a custom endpoint with custom headers defined which point to environment variables, something like this:

```
custom:
  - name: "Azure OpenAI - General Purpose"
    apiKey: "${LIBRECHAT_SUBSCRIPTION_KEY}"
    baseURL: "https://<custom_domain>/ai/azure-oaiv1"
    customParams:
      defaultParamsEndpoint: azureOpenAI
    headers:
      X-User-Identifier: "{{LIBRECHAT_USER_EMAIL}}"
      X-Application-Identifier: "LibreChat - Dev"
      api-key: "${LIBRECHAT_SUBSCRIPTION_KEY}"
    models:
      default:
        - "gpt-5-chat-2025-10-03"
        - "gpt-4.1-2025-04-14"
        - "gpt-4.1-mini-2025-04-14"
        - "gpt-4.1-nano-2025-04-14"
        - "gpt-4o-2024-11-20"
        - "gpt-4o-mini-2024-07-18"
      fetch: false
    summarize: false
    titleConvo: true
    titleModel: "gpt-4.1-nano-2025-04-14"
```

Then configure memory to point to this:

```
memory:
  disabled: false
  tokenLimit: 3000
  personalize: true
  messageWindowSize: 10
  agent:
    provider: "Azure OpenAI - General Purpose"
    model: "gpt-5-chat-2025-10-03"
```

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell
error: Memory Agent failed to process memory 401 status code (no body)
```

### Screenshots

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dustinhealy**
Closes #11012 

## Summary

This pull request introduces the ability to designate custom endpoints for usage with the Memory feature. This was previously not possible due to an architectural difference in the way agent runs are handled across normal chat completions and memory chat completions, such that `resolveHeaders` was not invoked, and as such, API keys passed through custom headers would not be expanded / replaced with their environment variables, as mentioned in #11012. Now that `resolveHeaders` has been implemented in `memory.ts`, the custom headers will be properly populated for custom endpoints and the memory feature will work as intended.

**User context propagation and header resolution:**

* The `user` object is now passed from the API request (`req.user`) into the agent client and down through the memory processing functions, including `processMemory` and `createMemoryProcessor` (`api/server/controllers/agents/client.js`, `packages/api/src/agents/memory.ts`). [[1]](diffhunk://#diff-8c99b1ddca0d7fa6758088ffec41bed3ff6ce185163505281c9e3de03450e8aaR679) [[2]](diffhunk://#diff-9e323913c7896d2ce82c27a66371c08510dc41bb273e54625687f08fac1b9b83R289) [[3]](diffhunk://#diff-9e323913c7896d2ce82c27a66371c08510dc41bb273e54625687f08fac1b9b83R305) [[4]](diffhunk://#diff-9e323913c7896d2ce82c27a66371c08510dc41bb273e54625687f08fac1b9b83R435) [[5]](diffhunk://#diff-9e323913c7896d2ce82c27a66371c08510dc41bb273e54625687f08fac1b9b83R444) [[6]](diffhunk://#diff-9e323913c7896d2ce82c27a66371c08510dc41bb273e54625687f08fac1b9b83R472)
* When preparing LLM configuration, the code now resolves and injects custom headers using the `resolveHeaders` and `createSafeUser` utilities (`packages/api/src/agents/memory.ts`). [[1]](diffhunk://#diff-9e323913c7896d2ce82c27a66371c08510dc41bb273e54625687f08fac1b9b83L17-R21) [[2]](diffhunk://#diff-9e323913c7896d2ce82c27a66371c08510dc41bb273e54625687f08fac1b9b83R372-R379)

## Change Type

- [x] New feature (non-breaking change which adds functionality)

## Testing

* Added a new test suite in `memory.spec.ts` to verify that environment variables and user placeholders in custom endpoint headers are correctly resolved, including cases with mixed placeholders, missing users, and missing configuration. [[1]](diffhunk://#diff-497e15550396f817869686c3e2a60952d493464ae23434b3447cc140edf68a3cR1-R254)

### Before (Memory not updated)

Screenshot 2026-01-05 at 12 09 08 PM

```
2026-01-05 10:35:40 error: Failed to fetch models from Portkey API The server responded with status 401: Request failed with status code 401
2026-01-05 10:35:44 error: Memory Agent failed to process memory 401 status code (no body)

Troubleshooting URL: https://js.langchain.com/docs/troubleshooting/errors/MODEL_AUTHENTICATION/
```

### After
Screenshot 2026-01-05 at 11 18 58 AM

#### Headers now properly being expanded and received at gateway (see dustin-test-expansion)

```json
"headers": {
    "accept": "application/json",
    "accept-encoding": "gzip, br",
    "accept-language": "*",
    "api-key": "du********ion", # dustin-test-expansion
    "cf-connecting-ip": "76.14.4.27",
    "cf-ipcountry": "US",
    "cf-ray": "9b9523c9fa46faa2",
    "cf-visitor": "{\"scheme\":\"https\"}",
    "connection": "Keep-Alive",
    "content-length": "2620",
    "content-type": "application/json",
    "host": "[api.portkey.ai](http://api.portkey.ai/)",
    "sec-fetch-mode": "cors",
    "user-agent": "CustomOpenAIClient/JS 5.8.2",
    "x-application-identifier": "LibreChat - Test",
    "x-forwarded-proto": "https",
    "x-real-ip": "76.14.4.27",
    "x-stainless-arch": "arm64",
    "x-stainless-lang": "js",
    "x-stainless-os": "MacOS",
    "x-stainless-package-version": "5.8.2",
    "x-stainless-retry-count": "0",
    "x-stainless-runtime": "node",
    "x-stainless-runtime-version": "v20.19.0",
    "x-user-identifier": "[me@me.com](mailto:me@me.com)"
  }
```

### **Test Configuration**:
```yaml
endpoints:
    custom:
        - name: 'Test Custom Endpoint Memory Expansion'
           apiKey: 'dummy'
           baseURL: 'https://api.portkey.ai/v1'
           headers:
             x-portkey-api-key: '${PORTKEY_API_KEY}'
             x-portkey-virtual-key: '${PORTKEY_OPENAI_VIRTUAL_KEY}'
             X-User-Identifier: '{{LIBRECHAT_USER_EMAIL}}'
             X-Application-Identifier: 'LibreChat - Test'
             api-key: '${TEST_CUSTOM_API_KEY}' # This should be expanded to dustin-test-expansion
           models:
             default:
               - 'gpt-4o-mini'
               - 'gpt-4o'
             fetch: false
  
memory:
  disabled: false
  tokenLimit: 3000
  personalize: true
  messageWindowSize: 10
  agent:
    provider: 'Test Custom Endpoint Memory Expansion'
    model: 'gpt-4o-mini'
```

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes

### CODE REVIEW

File: api/server/controllers/agents/client.js [hunk 1]
```diff
@@ -676,6 +676,7 @@ class AgentClient extends BaseClient {
         getFormattedMemories: db.getFormattedMemories,
       },
       res: this.options.res,
+      user: this.options.req.user,
```
Comment (danny-avila) [inline api/server/controllers/agents/client.js]: instead of passing `this.options.req.user`, can you utilize `createSafeUser` here?

Comment (danny-avila) [reply api/server/controllers/agents/client.js]: also consider adding test for this

File: packages/api/src/agents/memory.ts [hunk 2]
```diff
@@ -366,6 +369,14 @@ ${memory ?? 'No existing memories'}`;
       }
     }
 
+    const llmConfigWithHeaders = finalLLMConfig as OpenAIClientOptions;
+    if (llmConfigWithHeaders?.configuration?.defaultHeaders != null) {
+      llmConfigWithHeaders.configuration.defaultHeaders = resolveHeaders({
```
Comment (danny-avila) [inline packages/api/src/agents/memory.ts:374]: utilize `createSafeUser` in `api/server/controllers/agents/client.js` instead

**Review by danny-avila — CHANGES_REQUESTED** [review]
