### PR TITLE
🛠️ feat: Add Config Validation Bypass & Improve Error Handling

### LINKED ISSUE #9561: [Enhancement]: Invalid librechat.yaml should fail fast
### What features would you like to see added?

Currently the server will still start when you have an invalid `librechat.yaml` file.

Ideally the process would exit with an error if the configuration is invalid. This would allow the deployment pipeline to catch issues earlier and fail faster.

### More details

This was buried in our logs:

```
error: Invalid custom config file at /app/librechat.yaml:
LibreChat-API  | {
LibreChat-API  |   "issues": [iew Config   w Enable Watch
LibreChat-API  |     {
LibreChat-API  |       "received": "${FILE_STRATEGY}",
LibreChat-API  |       "code": "invalid_enum_value",
LibreChat-API  |       "options": [
LibreChat-API  |         "local",
LibreChat-API  |         "firebase",
LibreChat-API  |         "azure",
LibreChat-API  |         "azure_blob",
LibreChat-API  |         "openai",
LibreChat-API  |         "s3",
LibreChat-API  |         "vectordb",
LibreChat-API  |         "execute_code",
LibreChat-API  |         "mistral_ocr",
LibreChat-API  |         "azure_mistral_ocr",
LibreChat-API  |         "vertexai_mistral_ocr",
LibreChat-API  |         "text"
LibreChat-API  |       ],
LibreChat-API  |       "path": [
LibreChat-API  |         "fileStrategy"
LibreChat-API  |       ],
LibreChat-API  |       "message": "Invalid enum value. Expected 'local' | 'firebase' | 'azure' | 'azure_blob' | 'openai' | 's3' | 'vectordb' | 'execute_code' | 'mistral_ocr' | 'azure_mistral_ocr' | 'vertexai_mistral_ocr' | 'text', received '${FILE_STRATEGY}'"
LibreChat-API  |     }
LibreChat-API  |   ],
LibreChat-API  |   "name": "ZodError"
LibreChat-API  | }
```

### Which components are impacted by your request?

_No response_

### Pictures

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by berry-13**
## Summary

This PR introduces a `CONFIG_BYPASS_VALIDATION` option that lets the app continue with defaults even when custom config validation fails. Validation errors now either trigger an explicit exit or fall back gracefully, and logging has been streamlined for clearer diagnostics.

https://github.com/LibreChat-AI/librechat.ai/pull/456

Closes #9561

## Change Type

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Testing

checked with both a correct and invalid librechat.yaml

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.
- [x] A pull request for updating the documentation has been submitted.

### CODE REVIEW

File: api/server/services/Config/loadCustomConfig.js [hunk 1]
```diff
@@ -85,26 +85,32 @@ Please specify a correct \`imageOutputType\` value (case-sensitive).
...
+      logger.warn(`
 The Speech-to-text and Text-to-speech configuration format has recently changed.
 If you're getting this error, please refer to the latest documentation:
 
 https://www.librechat.ai/docs/configuration/stt_tts`);
-      }
+    }
 
-      i++;
+    if (process.env.CONFIG_BYPASS_VALIDATION === 'true') {
```
Comment (danny-avila) [inline api/server/services/Config/loadCustomConfig.js:103]: Requires documentation in docs repo

**Review by danny-avila — CHANGES_REQUESTED** [review]
