### PR TITLE
🔒 feat: Add Content Security Policy using Helmet middleware

### LINKED ISSUE #7110: [Enhancement]: Missing Content Security Policy
### What features would you like to see added?

Implementation of Content Security Policy (CSP) Headers. 

I am not sure how far this is possible as we are interacting with other interfaces on the backend as well.
I'm sure smarter people than me are going to know what needs to be done about this. 

### More details

We recently conducted a Pentest on Librechat and no critical vulnerabilities were found: 🎉
The only thing that got flagged was that the application currently lacks Content Security Policy headers in its HTTP responses, which exposes the application to potential security vulnerabilities like XSS attacks and clickjacking.

## These were the recommendations: 

To enhance the security of the website and protect against various attacks, it is recommended to configure
a Content Security Policy (CSP). Implementing a CSP helps mitigate risks associated with cross-site
scripting (XSS), clickjacking, and data injection attacks by instructing browsers on how to load and execute
content on your site.
This can be achieved by adding the following HTTP header to the server configuration:
`Content-Security-Policy: default-src 'self'; script-src 'self' https://trustedscripts.
example.com; object-src 'none'; frame-ancestors 'self';`
This example CSP configuration allows resources to be loaded only from the same origin and a trusted
script
source, while also preventing the use of plugins and embedding the site in frames from other origins.
Alternatively, if you prefer to add the CSP through the HTML document, you can use the following meta tag
within the <head> section of your HTML:
`<meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self'
https://trusted-scripts.example.com; object-src 'none'; frame-ancestors 'self';">`

### References
[https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html](https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html)
[https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP)

### Which components are impacted by your request?

General

### Pictures

Image

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### LINKED ISSUE #7406: [Bug]: Cannot register new account (Cloudflare Turnstile console error)
### What happened?

Following the instructions at https://www.librechat.ai/docs/quick_start/local_setup, I cannot register a new account in the locally Docker-hosted version of LibreChat I just spun up: the "Continue" button is disabled regardless of form content.

Image

In my browser console, I see 

`Uncaught (in promise) TurnstileError: [Cloudflare Turnstile] Invalid or missing type for parameter "sitekey", expected "string", got "undefined".`

The docker-compose.yml file I'm using specifies `ghcr.io/danny-avila/librechat-dev:latest` as the app container image (I'm using 829e1c5ea267). I notice this was very recently rebuilt after a [PR](https://github.com/danny-avila/LibreChat/pull/5987) merged introducing Turnstile support. I reviewed the PR since there is no Turnstile documentation in the docs site, and it appears this is supposed to be a no-op if I don't have Turnstile config (I do not). 

### Version Information

`ghcr.io/danny-avila/librechat-dev               latest    7bd4ac4f1d1c`

### Steps to Reproduce

1. Start docker container following instructions at https://www.librechat.ai/docs/quick_start/local_setup
2. Try to register a new account

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
Uncaught (in promise) TurnstileError: [Cloudflare Turnstile] Invalid or missing type for parameter "sitekey", expected "string", got "undefined".
    Oe https://challenges.cloudflare.com/turnstile/v0/api.js?onload=onloadTurnstileCallback&render=explicit:1
    c https://challenges.cloudflare.com/turnstile/v0/api.js?onload=onloadTurnstileCallback&render=explicit:1
    dr https://challenges.cloudflare.com/turnstile/v0/api.js?onload=onloadTurnstileCallback&render=explicit:1
    a https://challenges.cloudflare.com/turnstile/v0/api.js?onload=onloadTurnstileCallback&render=explicit:1
    g https://challenges.cloudflare.com/turnstile/v0/api.js?onload=onloadTurnstileCallback&render=explicit:1
    T https://challenges.cloudflare.com/turnstile/v0/api.js?onload=onloadTurnstileCallback&render=explicit:1
    Te http://localhost:3080/assets/vendor.BIxDWwK1.js:108
    Te http://localhost:3080/assets/vendor.BIxDWwK1.js:108
    tl http://localhost:3080/assets/vendor.BIxDWwK1.js:19
    xc http://localhost:3080/assets/vendor.BIxDWwK1.js:19
    yc http://localhost:3080/assets/vendor.BIxDWwK1.js:19
    w http://localhost:3080/assets/vendor.BIxDWwK1.js:10
    C http://localhost:3080/assets/vendor.BIxDWwK1.js:10
    requireScheduler_production_min http://localhost:3080/assets/vendor.BIxDWwK1.js:10
    requireScheduler_production_min http://localhost:3080/assets/vendor.BIxDWwK1.js:10
    requireScheduler http://localhost:3080/assets/vendor.BIxDWwK1.js:10
    requireReactDom_production_min http://localhost:3080/assets/vendor.BIxDWwK1.js:19
    requireReactDom http://localhost:3080/assets/vendor.BIxDWwK1.js:19
    requireClient http://localhost:3080/assets/vendor.BIxDWwK1.js:19
    <anonymous> http://localhost:3080/assets/vendor.BIxDWwK1.js:19
```

### Screenshots

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rubentalstra**
## Summary

- fix: https://github.com/danny-avila/LibreChat/issues/7406

This pull request introduces security enhancements and code quality improvements to the `api` package. The key changes include the addition of the `helmet` library to enforce HTTP security headers, reordering middleware for better maintainability, and minor adjustments to improve code readability and consistency.

### Security Enhancements:
* Added the `helmet` library to the dependencies in `package.json` and integrated it into the server to enforce a Content Security Policy (CSP) with directives for `defaultSrc`, `scriptSrc`, `objectSrc`, and `frameAncestors` to enhance security. (`api/package.json` - [[1]](diffhunk://#diff-d0ab9c1cc78fba971b5270314ad877706d340d099b42f46a406fc5de6a32fdf0R74) `api/server/index.js` - [[2]](diffhunk://#diff-a7e858ecd8004b310ac59b25e999ad677fba3cd712ab7f7da4f0aa5bf8d28cf4R5) [[3]](diffhunk://#diff-a7e858ecd8004b310ac59b25e999ad677fba3cd712ab7f7da4f0aa5bf8d28cf4L52-R88)

### Code Quality Improvements:
* Reordered middleware in `startServer` to improve readability and maintainability, ensuring logical grouping and consistent placement of middleware calls. (`api/server/index.js` - [api/server/index.jsL52-R88](diffhunk://#diff-a7e858ecd8004b310ac59b25e999ad677fba3cd712ab7f7da4f0aa5bf8d28cf4L52-R88))
* Simplified a warning message for disabled social logins by removing redundant phrasing. (`api/server/index.js` - [api/server/index.jsL52-R88](diffhunk://#diff-a7e858ecd8004b310ac59b25e999ad677fba3cd712ab7f7da4f0aa5bf8d28cf4L52-R88))
* Fixed a minor code consistency issue by replacing `==` with `===` for strict equality in the server's host check. (`api/server/index.js` - [api/server/index.jsL131-R151](diffhunk://#diff-a7e858ecd8004b310ac59b25e999ad677fba3cd712ab7f7da4f0aa5bf8d28cf4L131-R151))

Screenshot 2025-05-14 at 20 50 35

## Change Type

- [x] New feature (non-breaking change which adds functionality)

## Testing

Please describe your test process and include instructions so that we can reproduce your test. If there are any important variables for your testing configuration, list them here.

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.

### CODE REVIEW

File: api/server/index.js [hunk 1]
```diff
@@ -49,23 +52,34 @@ const startServer = async () => {
...
+  app.use(
+    helmet.contentSecurityPolicy({
+      directives: {
+        defaultSrc: ["'self'"], // allow everything from same origin by default
+        scriptSrc: ["'self'"], // only own scripts and a trusted external source
+        objectSrc: ["'none'"], // disallow plugin-based content
+        frameAncestors: ["'self'"], // prevent framing by other sites
+      },
+    }),
+  );
```
Comment (mawburn) [inline api/server/index.js]: fwiw, you can achieve this without adding a dependency. 

```suggestion
app.use((req, res, next) => {
  res.setHeader(
    'Content-Security-Policy',
    "default-src 'self'; script-src 'self'; object-src 'none'; frame-ancestors 'self'"
  );
  next();
});
```

Comment (rubentalstra) [reply api/server/index.js]: @mawburn I know that 😉, but I like the helmet package. but if @danny-avila does not want the package then I will off course remove it. but with the package there is more flexibility and a little easier for others to add new stuff to the header or the CSP setup in general.

Comment (mawburn) [reply api/server/index.js]: Cool, yeah he has the say obviously. I just noticed it as a change above my group's PR and figured I'd mention it. 

I get the reasons for some things like this, but this one in particular feels very `left-pad` to me since the actual middleware is so simple. IMO, it's also more clear because I don't need to go check for possible side effects with the library, for instance.

Comment (danny-avila) [reply api/server/index.js]: I prefer not having the extra dependency and also add an .env variable to specify the policy. if not use, the default one @mawburn suggested

File: api/server/index.js [hunk 2]
```diff
@@ -49,23 +52,34 @@ const startServer = async () => {
...
-  app.use(mongoSanitize());
   app.use(express.urlencoded({ extended: true, limit: '3mb' }));
-  app.use(staticCache(app.locals.paths.dist));
-  app.use(staticCache(app.locals.paths.fonts));
-  app.use(staticCache(app.locals.paths.assets));
-  app.set('trust proxy', trusted_proxy);
+  app.use(mongoSanitize());
   app.use(cors());
   app.use(cookieParser());
+  app.use(
```
Comment (danny-avila) [inline api/server/index.js:67]: https://github.com/danny-avila/LibreChat/pull/7377#discussion_r2091181431

**Review by danny-avila — CHANGES_REQUESTED** [review]

File: api/server/index.js (hunk 1 above)
Comment (danny-avila) [reply api/server/index.js]: OK we discussed, omit the .env var for now. Helmet still applies other security-related headers by default when using it like you are though, so unless there's a way to disable them all (introduce unknown side effects), we should omit it. Still discussing with @rubentalstra

Comment (rubentalstra) [reply api/server/index.js]: @danny-avila as discussed. keep using package [helmet](https://helmetjs.github.io/) for future easy integration or addition.

default security-related headers are disabled by using the `useDefaults: false`

Comment (mawburn) [reply api/server/index.js]: @danny-avila @rubentalstra 

I apologize if I wasn't clear with the library I mentioned. What I meant by: 

> feels very `left-pad` to me

Was that `left-pad` was a library that broke just about everything npm related back in 2016. The damages were in the billions of dollars literally overnight because some guy decided to take down his open source library because nobody was supporting him financially. (or something like that)

https://en.wikipedia.org/wiki/Npm_left-pad_incident

It broke things like React, Babel, and a ton of other stuff because so many peer deps relied on it. The underlying issue of a developer being able to remove a package overnight like that was fixed almost immediately, so that's not relevant. 

What I meant by it was that the library itself was only like 11 lines of code and shouldn't have been used in the first place. It also highlighted the overuse of grabbing libraries to do every little thing. While people can't rip down repos from npm anymore, this is still sort of relevant if a new major version comes out or some kind of significant security hole or something is discovered. Plus the overall over reliance on 3rd party packages.

---

This might not be relevant to the decision to keep helmet, I'm cool with that if you think there are other benefits. I was just adding my 2¢ and wanted to clear up what I meant by what I said above.

**Review by danny-avila — APPROVED** [review]

**Review by danny-avila — APPROVED** [review]
