### PR TITLE
🗑️ fix: Remove All User Metadata on Deletion

### LINKED ISSUE #10540: [Bug]: All metadata is not removed on user deletion
### What happened?

Librechat supports user deletion which also deletes a lot of metadata associated with a user. This is a very nice feature. However, not all user metadata is deleted when a user is deleted. This is a problem with respect to GDPR concerns. 

I have made PR to fix the issue here: https://github.com/danny-avila/LibreChat/pull/10534

### Version Information

8.0.1rc

### Steps to Reproduce

Delete a user via the the delete account button in the UI under settings.

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

Log output is not relevant but the relevant deletion code is in `LibreChat/api/server/controllers/UserController.js`. Note that `deleteUserController` does not include deletion of 
* assistants
* agents
* memories
* conversation tags
* actions
* prompts

### Screenshots

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by WhammyLeaf**
I have noticed that a lot of user metadata is not actually releted on user deletion. For the sake of GDPR this should be fixed, which this PR attempts to do. 

# Pull Request Template

⚠️ Before Submitting a PR, Please Review:
- Please ensure that you have thoroughly read and understood the [Contributing Docs](https://github.com/danny-avila/LibreChat/blob/main/.github/CONTRIBUTING.md) before submitting your Pull Request.

⚠️ Documentation Updates Notice:
- Kindly note that documentation updates are managed in this repository: [librechat.ai](https://github.com/LibreChat-AI/librechat.ai)

## Summary

Please provide a brief summary of your changes and the related issue. Include any motivation and context that is relevant to your changes. If there are any dependencies necessary for your changes, please list them here.

## Change Type

Please delete any irrelevant options.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Translation update

## Testing

Please describe your test process and include instructions so that we can reproduce your test. If there are any important variables for your testing configuration, list them here.

## Checklist

Please delete any irrelevant options.

- [X] My code adheres to this project's style guidelines
- [X] I have performed a self-review of my own code
- [X] I have commented in any complex areas of my code
- [X] I have made pertinent documentation changes
- [ ] My changes do not introduce new warnings
- [ ] I have written tests demonstrating that my changes are effective or that my feature works
- [ ] Local unit tests pass with my changes
- [X] Any changes dependent on mine have been merged and published in downstream modules.
- [] A pull request for updating the documentation has been submitted.

### CODE REVIEW

File: api/server/controllers/UserController.js [hunk 1]
```diff
@@ -96,6 +108,40 @@ const deleteUserFiles = async (req) => {
...
+        // Continue deleting other agents
+      }
+    });
+    await Promise.allSettled(promises);
+  } catch (error) {
+    logger.error('[deleteUserAgents] General error:', error);
+  }
+};
+
+const deleteUserPrompts = async (req, userId) => {
```
Comment (danny-avila) [inline api/server/controllers/UserController.js]: this should be a method in `packages/data-schemas`

File: api/server/controllers/UserController.js [hunk 2]
```diff
@@ -96,6 +108,40 @@ const deleteUserFiles = async (req) => {
   }
 };
 
+const deleteUserAgents = async (userId) => {
```
Comment (danny-avila) [inline api/server/controllers/UserController.js]: this should be a method in `packages/data-schemas`

**Review by danny-avila — CHANGES_REQUESTED** [review]

File: api/server/controllers/UserController.js (hunk 1 above)
Comment (WhammyLeaf) [reply api/server/controllers/UserController.js]: I put this and the other helper method in the relevant package

**Review by danny-avila — COMMENTED** [review]
This looks like a solid and necessary fix for GDPR compliance. The implementation covers the major user-generated entities (Agents, Prompts, Assistants, Memories, etc.) that were previously missed.

I checked `api/models/Prompt.js` and confirmed that `ObjectId` is imported, so the usage in `deleteUserPrompts` is correct.

A couple of minor observations/questions:

1.  **OpenAI Assistants:** `Assistant.deleteMany` cleans up the local DB records. If these assistants were created using a user-provided API key on OpenAI, this operation leaves the assistant active on OpenAI's side. This is probably acceptable (and safer/faster) for a local account deletion, but it's worth noting that "full" deletion of the external resource isn't happening here.
2.  **Threads:** You removed `/* TODO: Delete Assistant Threads */`. I assume `deleteConvos` handles this since threads are essentially conversations?

The use of `Promise.allSettled` in the helper functions is a good choice to ensure one failure doesn't block the entire cleanup process.

LGTM!
