### PR TITLE
⚡ feat: Gemini-1.5 Flash, `gpt-4o` imports, `modelSpec` greeting fix

### LINKED ISSUE #2714: [Bug]: Need Padding around modelSpec greeting
### What happened?

modelSpec greeting extends to the far sides of the conversation pane.

image

### Steps to Reproduce

create a modelSpec with a long greeting name.

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### Screenshots

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #2715: Enhancement: Add New Gemini 1.5 Flash Model
### What features would you like to see added?

At Google I/O, a new model called Gemini 1.5 Flash (a lightweight model optimized for speed and efficiency) was introduced. I would like to add support for this model in LibreChat so we can easily use it through the Google AI Studio API

### More details

Gemini 1.5 Flash is available in public preview with a 1 million token context window in Google AI Studio and Vertex AI.

more detailed information available here:
https://deepmind.google/technologies/gemini/flash/

### Which components are impacted by your request?

_No response_

### Pictures

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #2718: [Bug]: Importing gpt-4o discussions "marks them" as gpt-3.5
### What happened?

Importing the following discussion

```
  ▽ [0]: {title: "title", create_time: 1715768065.068312, update_time: 1715770957.006343, mapping: {…}, moderation_results: [], current_node: "03f88f26-ea8d-460d-94c3-1…", …}
      title: "title"
      create_time: 1715768065.068312
      update_time: 1715770957.006343
    ▶ mapping: {"694f4d04-e68b-4b5c-9f51-5e11b0232636": {…}, "aaa14c7c-8f97-455a-9ad7-65d698bd4959": {…}, "aaa2b9ee-292c-4492-a61e-39f2195fd1b2": {…}, "0a9b4450-1119-4131-95c6-acbbd1744241": {…}, …}
      moderation_results: []
      current_node: "03f88f26-ea8d-460d-94c3-1939a0062145"
      plugin_ids: null
      conversation_id: "15d1b3ce-f8a3-4810-a145-6ccae5f2a0ea"
      conversation_template_id: null
      gizmo_id: null
      is_archived: false
      safe_urls: []
      default_model_slug: "gpt-4o"
      id: "15d1b3ce-f8a3-4810-a145-6ccae5f2a0ea"
```

with e.g. this message

```
    ▽ mapping: {"694f4d04-e68b-4b5c-9f51-5e11b0232636": {…}, "aaa14c7c-8f97-455a-9ad7-65d698bd4959": {…}, "aaa2b9ee-292c-4492-a61e-39f2195fd1b2": {…}, "0a9b4450-1119-4131-95c6-acbbd1744241": {…}, …}
      ▷ "694f4d04-e68b-4b5c-9f51-5e11b0232636": {id: "694f4d04-e68b-4b5c-9f51-5e11b0232636", message: {…}, parent: "aaa14c7c-8f97-455a-9ad7-65d698bd4959", children: […]}
      ▷ "aaa14c7c-8f97-455a-9ad7-65d698bd4959": {id: "aaa14c7c-8f97-455a-9ad7-65d698bd4959", message: null, parent: null, children: […]}
      ▶ "aaa2b9ee-292c-4492-a61e-39f2195fd1b2": {id: "aaa2b9ee-292c-4492-a61e-39f2195fd1b2", message: {…}, parent: "694f4d04-e68b-4b5c-9f51-5e11b0232636", children: […]}
      ▽ "0a9b4450-1119-4131-95c6-acbbd1744241": {id: "0a9b4450-1119-4131-95c6-acbbd1744241", message: {…}, parent: "aaa2b9ee-292c-4492-a61e-39f2195fd1b2", children: […]}
          id: "0a9b4450-1119-4131-95c6-acbbd1744241"
        ▽ message: {id: "0a9b4450-1119-4131-95c6-acbbd1744241", author: {…}, create_time: 1715768070.869453, update_time: null, content: {…}, status: "finished_successfully", end_turn: true, weig…: …, …}
            id: "0a9b4450-1119-4131-95c6-acbbd1744241"
          ▽ author: {role: "assistant", name: null, metadata: {}}
              role: "assistant"
              name: null
              metadata: {}
            create_time: 1715768070.869453
            update_time: null
          ▽ content: {content_type: "text", parts: […]}
              content_type: "text"
            ▽ parts: ["…"]
                [0]: "……"
            status: "finished_successfully"
            end_turn: true
            weight: 1.0
          ▽ metadata: {finish_details: {…}, citations: [], gizmo_id: null, is_complete: true, message_type: null, model_slug: "gpt-4o", default_model_slug: "gpt-4o", pad: "AAAAAAAAAAAAAAAAAAAAA", …}
            ▽ finish_details: {type: "stop", stop_tokens: […]}
                type: "stop"
              ▽ stop_tokens: [200002]
                  [0]: 200002
              citations: []
              gizmo_id: null
              is_complete: true
              message_type: null
              model_slug: "gpt-4o"
              default_model_slug: "gpt-4o"
              pad: "AAAAAAAAAAAAAAAAAAAAA"
              parent_id: "aaa2b9ee-292c-4492-a61e-39f2195fd1b2"
              request_id: "88425c646f6c70ff-HEL"
              timestamp_: "absolute"
            recipient: "all"
          parent: "aaa2b9ee-292c-4492-a61e-39f2195fd1b2"
        ▽ children: ["aaa28231-f300-4fed-800e-751ceb803aee"]
            [0]: "aaa28231-f300-4fed-800e-751ceb803aee"
```

correctly sets metadata

```md
# Conversation
- conversationId: cf8e44ea-a57b-4725-ac29-1768a7a9c08a
- endpoint: openAI
- title: Disagreements Foster Understanding
- exportAt: 14:11:21 GMT+0300 (Eastern European Summer Time)

## Options
- presetId: null
- model: gpt-4o
...
```

but not the assistant name

```md
## History
**user:**
Hey, I need some help.

...

**GPT-3.5:**
Certainly! Here’s an elaboration and flow of the points you remembered in a way that fits the discussion context:
```

### Steps to Reproduce

1. Export OpenAI data
2. Import them to LibreChat
3. "Find a suitable discussion"
4. Export it

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### Screenshots

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by danny-avila**
## Summary

Closes #2714
Closes #2715
Closes #2718

## Change Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.
- [x] A pull request for updating the documentation has been submitted.

### CODE REVIEW

File: api/server/utils/import/importers.js [hunk 1]
```diff
@@ -202,7 +202,7 @@ function processConversation(conv, importBatchBuilder, requestUserId) {
     const isCreatedByUser = role === 'user';
     let sender = isCreatedByUser ? 'user' : 'GPT-3.5';
     const model = mapping.message.metadata.model_slug || openAISettings.model.default;
-    if (model === 'gpt-4') {
+    if (model.includes('gpt-4')) {
       sender = 'GPT-4';
```
Comment (stdedos) [inline api/server/utils/import/importers.js:206]: "Technically", it's GPT-4 _and_ GPT-4o :sweat_smile: (ofc I haven't looked up what `model` looks like)

Comment (danny-avila) [reply api/server/utils/import/importers.js:206]: this works for when the model is vanilla "gpt-4" as well as "gpt-4o"

Comment (danny-avila) [reply api/server/utils/import/importers.js:206]: I see what you mean about differentiating the sender, I'll think about that soon, as that would mean a few other changes app-wide

Comment (stdedos) [reply api/server/utils/import/importers.js:206]: I mean, tbh, I would'be just slapped all `gpt-4-1106-preview` strings into a huge lookup table (and hide the actual model name e.g. under a hover on the username).

At least for the OpenAI models, that go like

* `gpt-4o-2024-05-13`
* `gpt-4-1106-preview`
* `gpt-3.5-turbo`

I'd try e.g.

```js
function extractUsername(modelName) {
    // Check for specific model name patterns and return corresponding usernames
    if (modelName.startsWith('gpt-4o-')) {
        return 'GPT-4o';
    } else if (modelName.startsWith('gpt-4-')) {
        return 'GPT-4';
    } else if (modelName.startsWith('gpt-3.5-turbo')) {
        return 'GPT-3';
    }

    ...
}
```

and/or something "smarter" (which ofc you can support with tests)

Ofc, up to you, the project, and your time :pray: (and things I haven't seen, since I haven't really dug the source)
